# Generated by Django 5.2.9 on 2025-12-18 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-start_time'], 'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True, verbose_name='会话时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('focus_time', models.IntegerField(default=25, verbose_name='专注时长（分钟）')),
                ('break_time', models.IntegerField(default=5, verbose_name='休息时长（分钟）')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '番茄钟',
                'verbose_name_plural': '番茄钟',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资料名称')),
                ('description', models.TextField(blank=True, verbose_name='资料描述')),
                ('material_type', models.CharField(choices=[('text', '文本/文档'), ('video', '视频'), ('audio', '音频'), ('link', '网页链接'), ('other', '其他')], default='text', max_length=20, verbose_name='资料类型')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径或链接')),
                ('estimated_time', models.IntegerField(default=0, verbose_name='预计学习时长（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '学习资料',
                'verbose_name_plural': '学习资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name='复习日期')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course', verbose_name='课程')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.studymaterial', verbose_name='学习资料（可选）')),
            ],
            options={
                'verbose_name': '复习计划',
                'verbose_name_plural': '复习计划',
                'ordering': ['review_date'],
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.studymaterial', verbose_name='学习资料（可选）'),
        ),
    ]
