# Generated by Django 4.2.27 on 2025-12-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_studysession_options_pomodorosession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='knowledgepoint',
            options={'verbose_name': '知识点', 'verbose_name_plural': '知识点'},
        ),
    ]
